title: Tosti
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#010602'
    - '#016D94'
    - '#003244'
    - '#60A0BC'
    - '#FEE1D4'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  version: null
  bucket: null
  domain: null
name: 'TOSTI '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.94527
layout_spectrum: 0.00085
