name: 'TOSTI '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.94527
title: Tosti
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000501'
    - '#005e7a'
    - '#478cab'
    - '#e4c4b7'
    - '#90644b'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
