typography_spectrum: 0.94527
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#010602'
    - '#016D94'
    - '#003244'
    - '#60A0BC'
    - '#FEE1D4'
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00085
analytics:
  twitter: null
  google: null
  facebook: null
name: 'TOSTI '
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - name: photography
    url: tostistudios.com
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: fuck in love u
purpose: []
