name: 'TOSTI '
favicon: null
layout_spectrum: 0.12413088278844953
typography_spectrum: 0.94527
title: The Music of David Tosti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000501'
    - '#005e7a'
    - '#478cab'
    - '#e4c4b7'
    - '#90644b'
  brandStrength: 1
  lightness: 0.953910042764619
  saturation: 0.7033716251607984
  rhythmicContrast: 0.5
purpose: []
