name: 'TOSTI '
favicon: null
layout_spectrum: 0.12413088278844953
typography_spectrum: 0.26526707015000284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10846626898273826
  lightness: 0.953910042764619
  saturation: 0.7033716251607984
  rhythmicContrast: 0.9302793475799263
purpose: []
